# Veřejná konfigurace eLKA agenta
git:
  platform: github # Možnosti: github, gitea
  repo_url: "user/lore-universe"

ai:
  provider: gemini # Možnosti: gemini, ollama
  providers:
    gemini:
      models:
        validator: "gemini-1.5-flash-latest"
        archivist: "gemini-1.5-flash-latest"
        generator: "gemini-1.5-pro-latest"
    ollama:
      base_url: "http://localhost:11434"
      models:
        validator: "llama3"
        archivist: "llama3"
        generator: "llama3"

core:
  rules_path: "Pokyny/"

logging:
  level: "INFO"
  file: "elka_agent.log"
