name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r elka-studio/backend/requirements.txt
        pip install ruff pytest

    - name: Run Linter (Ruff)
      run: ruff check elka-studio/backend/

    - name: Run Formatter Check (Ruff)
      run: ruff format --check elka-studio/backend/

    - name: Run Tests (Pytest)
      run: pytest elka-studio/backend/tests/
